<?php

/**
 * PluginPromoCampaignTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPromoCampaignTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPromoCampaignTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPromoCampaign');
    }
}