
pc_campaigns_activate:
  url: /api/v2/carts/:id/promocodes/activate
  class: sfRequestRoute
  param: { module: pcPromocodes, action: activate }
  options:
    credentials: tck-onlinesales-api-cart-items-edit
    #secure: false
  requirements:
    id: \d+
    sf_method: [POST]

##
## BACKEND
##

pc_campaigns:
  class: sfDoctrineRouteCollection
  options:
    model:                PromoCampaign
    module:               pcCampaigns
    prefix_path:          /promo_campaigns
    column:               id
    with_wildcard_routes: true
