generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PromoCampaign
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          pc_campaigns
    with_doctrine_route:   true
    actions_base_class:    sfActions
    i18n_catalogue:        pc_campaigns

    config:
      actions:
      fields:
        expiration: { label: Expire at }
        show_count_promo_codes: { label: Codes count }
        MemberCardType: { label: Card type }
      list:
        object_actions:
          _show: ~
          _edit: ~
          export:
            action: export
            label: Export
            ui-icon: arrowstop-1-s
        display: [title, name, expiration, MemberCardType, _show_count_promo_codes]
      filter: ~
      form: ~
      new:
        title: New Campaign
        display: 
          Campaign: [title, name, expiration, card_type_id, card_price_id, codes_count]
          Codes:    [_show_promo_codes]
      edit: ~
      show:
        display:
          Campaign: [title, name, expiration, MemberCardType, Price]
          Codes:    [_show_promo_codes]
