
PromoCampaign:
  actAs:
    Timestampable: ~
  columns:
    title:
      type: string(255)
    name:
      type: string(255)
      notnull: true
      unique: true
    expiration:
      type: timestamp
      notnull: true
    card_type_id:
      type: integer
      notnull: true
    card_price_id:
      type: integer
      notnull: true
    codes_count:
      type: integer
      default: 0
      notnull: true
  relations:
    MemberCardType:
      foreignType: one
      onDelete: SET NULL
      foreignAlias: PromoCampaigns
      local: card_type_id
    Price:
      foreignType: one
      onDelete: SET NULL
      foreignAlias: PromoCampaigns
      local: card_price_id
      

PromoCode:
  actAs:
    Timestampable: ~
  columns:
    code:
      type: string(255)
      notnull: true
      unique: true
    campaign_id:
      type: integer
      notnull: true
    account_id:
      type: integer
    activation_date:
      type: timestamp
  relations:
    Account:
      class: Contact
      foreignAlias: PromoCodes
      local: account_id
    PromoCampaign:
      foreignAlias: PromoCodes
      local: campaign_id
      onDelete: CASCADE
